# Google Cloud Build configuration for Blog Writer SDK
# IMPORTANT: This build should only be triggered via Cloud Build triggers, not manually.
# Manual builds are prevented by requiring trigger-specific substitution variables.

steps:
  # Verify this is a trigger-based build (not manual)
  # Triggers set specific substitution variables that manual builds don't have
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        if [ -z "$${_SERVICE_NAME}" ] || [ "$${_SERVICE_NAME}" = "blog-writer-api-dev" ] && [ -z "$${_ENV}" ]; then
          echo "ERROR: This build must be triggered via Cloud Build trigger, not manually."
          echo "Manual builds are not allowed. Please use the configured Cloud Build trigger."
          exit 1
        fi
        echo "✅ Build triggered via Cloud Build trigger ($${_SERVICE_NAME} in $${_ENV})"
  
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/blog-writer-sdk/blog-writer-sdk:$BUILD_ID',
      '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/blog-writer-sdk/blog-writer-sdk:latest',
      '.'
    ]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/blog-writer-sdk/blog-writer-sdk:$BUILD_ID']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/blog-writer-sdk/blog-writer-sdk:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', '${_SERVICE_NAME}',
      '--image', '${_REGION}-docker.pkg.dev/$PROJECT_ID/blog-writer-sdk/blog-writer-sdk:$BUILD_ID',
      '--region', '${_REGION}',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8000',
      '--memory', '2Gi',
      '--cpu', '2',
      '--min-instances', '0',
      '--max-instances', '100',
      '--concurrency', '80',
      '--timeout', '900',
      '--startup-probe', 'timeoutSeconds=3,periodSeconds=5,failureThreshold=60,httpGet.path=/health,httpGet.port=8000',
      '--set-env-vars', 'PYTHONUNBUFFERED=1',
      '--update-secrets', '/secrets/env=blog-writer-env-${_ENV}:latest,OPENAI_API_KEY=OPENAI_API_KEY:latest,ANTHROPIC_API_KEY=ANTHROPIC_API_KEY:latest,STABILITY_AI_API_KEY=STABILITY_AI_API_KEY:latest'
    ]

# Store images in Container Registry
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/blog-writer-sdk/blog-writer-sdk:$BUILD_ID'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/blog-writer-sdk/blog-writer-sdk:latest'

# Substitution variables
substitutions:
  _REGION: 'europe-west9'  # Default to dev region, will be overridden by trigger substitutions
  _ENV: 'dev'
  _SERVICE_NAME: 'blog-writer-api-dev'  # Default to dev service, will be overridden by trigger substitutions

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: '100'

# Build timeout
timeout: '1200s'

