# Google Cloud Build configuration for Blog Writer SDK
# IMPORTANT: This build should only be triggered via Cloud Build triggers, not manually.
# Manual builds are prevented by requiring trigger-specific substitution variables.

steps:
  # Verify this is a trigger-based build (not manual)
  # Cloud Build triggers automatically set substitution variables (_REGION, _ENV, _SERVICE_NAME)
  # Manual builds don't have these variables set correctly, so we can detect them
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        # Check if trigger-specific substitution variables are set (indicates trigger-based build)
        # Triggers set _REGION, _ENV, _SERVICE_NAME via trigger substitutions
        # Manual builds typically don't set these or use default values
        if [ -z "${_REGION}" ] || [ -z "${_ENV}" ] || [ -z "${_SERVICE_NAME}" ]; then
          echo "❌ ERROR: This build must be triggered via Cloud Build trigger, not manually."
          echo "Manual builds are not allowed. Please use the configured Cloud Build trigger."
          echo ""
          echo "To deploy, push to the appropriate branch:"
          echo "  - Push to 'develop' branch → Deploys to dev environment"
          echo "  - Push to 'main' branch → Deploys to production environment"
          exit 1
        fi
        echo "✅ Build triggered via Cloud Build trigger"
        echo "✅ Deploying ${_SERVICE_NAME} to ${_REGION} (env: ${_ENV})"
  
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/blog-writer-sdk/blog-writer-sdk:$BUILD_ID',
      '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/blog-writer-sdk/blog-writer-sdk:latest',
      '.'
    ]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/blog-writer-sdk/blog-writer-sdk:$BUILD_ID']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/blog-writer-sdk/blog-writer-sdk:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', '${_SERVICE_NAME}',
      '--image', '${_REGION}-docker.pkg.dev/$PROJECT_ID/blog-writer-sdk/blog-writer-sdk:$BUILD_ID',
      '--region', '${_REGION}',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8000',
      '--memory', '2Gi',
      '--cpu', '2',
      '--min-instances', '0',
      '--max-instances', '100',
      '--concurrency', '80',
      '--timeout', '900',
      '--startup-probe', 'timeoutSeconds=3,periodSeconds=5,failureThreshold=60,httpGet.path=/health,httpGet.port=8000',
      '--set-env-vars', 'PYTHONUNBUFFERED=1,TESTING_MODE=${_TESTING_MODE}',
      '--update-secrets', '/secrets/env=blog-writer-env-${_ENV}:latest,OPENAI_API_KEY=OPENAI_API_KEY:latest,ANTHROPIC_API_KEY=ANTHROPIC_API_KEY:latest,STABILITY_AI_API_KEY=STABILITY_AI_API_KEY:latest'
    ]

# Store images in Container Registry
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/blog-writer-sdk/blog-writer-sdk:$BUILD_ID'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/blog-writer-sdk/blog-writer-sdk:latest'

# Substitution variables
substitutions:
  _REGION: 'europe-west9'  # Default to dev region, will be overridden by trigger substitutions
  _ENV: 'dev'
  _SERVICE_NAME: 'blog-writer-api-dev'  # Default to dev service, will be overridden by trigger substitutions
  _TESTING_MODE: 'false'  # Default to false, set to 'true' for develop branch testing

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: '100'

# Build timeout
timeout: '1200s'

