# Multi-environment Cloud Build configuration
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/blog-writer-sdk/blog-writer-sdk:${COMMIT_SHA}',
      '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/blog-writer-sdk/blog-writer-sdk:${_ENVIRONMENT}-latest',
      '.'
    ]

  # Push the container images
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/blog-writer-sdk/blog-writer-sdk:${COMMIT_SHA}']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/blog-writer-sdk/blog-writer-sdk:${_ENVIRONMENT}-latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'api-ai-blog-writer${_SERVICE_SUFFIX}',
      '--image', '${_REGION}-docker.pkg.dev/$PROJECT_ID/blog-writer-sdk/blog-writer-sdk:${COMMIT_SHA}',
      '--region', '${_REGION}',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8000',
      '--memory', '${_MEMORY}',
      '--cpu', '${_CPU}',
      '--min-instances', '${_MIN_INSTANCES}',
      '--max-instances', '${_MAX_INSTANCES}',
      '--concurrency', '${_CONCURRENCY}',
      '--timeout', '900',
      '--service-account', 'blog-writer-${_ENVIRONMENT}@$PROJECT_ID.iam.gserviceaccount.com',
      '--set-env-vars', 'PORT=8000,PYTHONUNBUFFERED=1,ENVIRONMENT=${_ENVIRONMENT}',
      '--set-secrets', '/secrets/env=blog-writer-env-${_ENVIRONMENT}:latest'
    ]

# Store images in Artifact Registry
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/blog-writer-sdk/blog-writer-sdk:${COMMIT_SHA}'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/blog-writer-sdk/blog-writer-sdk:${_ENVIRONMENT}-latest'

# Default substitution variables
substitutions:
  _REGION: 'us-east1'
  _ENVIRONMENT: 'dev'
  _SERVICE_SUFFIX: '-dev'
  _MEMORY: '1Gi'
  _CPU: '1'
  _MIN_INSTANCES: '0'
  _MAX_INSTANCES: '5'
  _CONCURRENCY: '10'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: '100'

# Build timeout
timeout: '1200s'
