name: deploy-staging-on-staging
description: Deploy to staging environment on staging branch pushes
repositoryEventConfig:
  push:
    branch: "^staging$"
  repository: projects/api-ai-blog-writer/locations/europe-west9/connections/europe-west9-paris/repositories/tindevelopers-api-blogwriting-python-gcr
  repositoryType: GITHUB
filename: cloudbuild.yaml
substitutions:
  _REGION: europe-west9
  _ENV: staging
  _SERVICE_NAME: blog-writer-api-staging

