name: Deploy to Railway

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allow manual deployment

jobs:
  deploy:
    name: Deploy to Railway
    runs-on: ubuntu-latest
    
    # Run deployment on main branch pushes
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Railway CLI
      run: |
        curl -fsSL https://railway.app/install.sh | bash
        echo "$HOME/.railway/bin" >> $GITHUB_PATH
    
    - name: Deploy to Railway
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: |
        railway login --token $RAILWAY_TOKEN
        railway up --detach
    
    - name: Get deployment URL
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: |
        railway login --token $RAILWAY_TOKEN
        echo "🚀 Deployment URL: $(railway domain)"
    
    - name: Health check
      run: |
        # Wait for deployment to be ready
        sleep 30
        
        # Get the deployment URL
        DEPLOY_URL=$(railway domain 2>/dev/null || echo "")
        
        if [ -n "$DEPLOY_URL" ]; then
          echo "Testing health endpoint: $DEPLOY_URL/health"
          
          # Retry health check up to 5 times
          for i in {1..5}; do
            if curl -f "$DEPLOY_URL/health" > /dev/null 2>&1; then
              echo "✅ Health check passed!"
              curl -s "$DEPLOY_URL/health" | jq '.'
              break
            else
              echo "⏳ Health check attempt $i failed, retrying in 10s..."
              sleep 10
            fi
          done
        else
          echo "⚠️ Could not retrieve deployment URL"
        fi
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

  notify:
    name: Deployment Notification
    runs-on: ubuntu-latest
    needs: [deploy]
    if: always()
    
    steps:
    - name: Deployment Success
      if: needs.deploy.result == 'success'
      run: |
        echo "🎉 BlogWriter SDK deployed successfully!"
        echo "✅ All systems operational"
    
    - name: Deployment Failed
      if: needs.deploy.result == 'failure'
      run: |
        echo "❌ Deployment failed"
        echo "Please check the logs for details"
        exit 1
